### ISSUE TITLE
janky when dragin the sheet up and down

### ISSUE THREAD

**Issue by Isakdl** [vaban-ru/vue-bottom-sheet#11]
When dragging the sheet down and then up again, the sheet freezes in the down position and then jumps back up as soon you start dragging down again.

**Comment by AlbertIspiryan-dev** [comment]
@Isakdl if you will set:
```
  &__content {
    height: 100%;
  }
}
```
It will fix this issue.

**Comment by vaban-ru** [comment]
Please try version 3.0
