### ISSUE TITLE
Bottom sheet flickers when scrolling inside iOS/safari

### ISSUE THREAD

**Issue by volkov-web** [vaban-ru/vue-bottom-sheet#27]
When scrolling inside bottom sheet flickers on iOS/safari
 

https://user-images.githubusercontent.com/79129581/216598678-7ddaa56b-32c3-4c0d-ba10-453089275e48.MP4

**Comment by WhatzzUpp** [comment]
+1 have the same issue

**Comment by Pajicc** [comment]
+1 same issue. Any news about this one?

**Comment by tohaosipow** [comment]
+1

**Comment by tohaosipow** [comment]
Починил в своем форке и еще сделал работу с nuxt
